# Generated by Django 5.2.6 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.URLField(default='static/images/batman.png', max_length=800),
        ),
    ]
