# Generated by Django 5.2.6 on 2025-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_review_unique_together_cart_order_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(default='static/images/ctrlPlay.png', max_length=800),
        ),
    ]
